### ISSUE TITLE
is this outdated?

### ISSUE THREAD

**Issue by usoppu** [boxcast/boxcast-sdk-js#21]
the sample code on the readme doesnt work.
providing an account id and channel yields empty results.
// api.channels.list(account_id, {
      //   s: 'name', // sort by
      //   l: 20,     // page limit
      //   p: 0       // page number
      // }).then((r) => console.log(r.pagination, r.data));
      //
      // api.broadcasts.list(channel_id, {
      //   q: 'timeframe:current',
      //   s: '-starts_at',
      //   l: 20,
      //   p: 0
      // }).then((r) => console.log(r.pagination, r.data));

**Comment by JHartman5** [comment]
I just tried this myself and it seems to be working fine. Keep a couple of things in mind:
1. The example above has `timeframe:current` in the query, so if you don't have any active broadcasts, it will return an empty array. You can change the query as described [here](https://boxcast.github.io/boxcast_api/#search) and [here](https://boxcast.github.io/boxcast_api/#broadcasts-list).
2. The broadcasts query only returns public broadcasts, so if your broadcasts are private, they won't show up.

Can you provide a more complete example with actual IDs that you expect to work?

**Comment by bikegriffith** [comment]
@usoppu The sample code in the readme should work fine -- you just need to make sure you have the proper account ID and channel ID for an active BoxCast account with those resources created/scheduled.

If you are having trouble finding your account/channel ID, or you suspect some other bug that you want us to look more deeply at, you can open a support ticket with our engineering staff @ https://www.boxcast.com/dev-support

**Comment by usoppu** [comment]
I couldn't get it to work. I ended up using a GET method without the SDK
